version: '3.7'

services:
  rhythm-player:
    build: .
    container_name: rhythm-player
    ports:
      - "18003:8000"
    volumes:
      - ./music:/app/music
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
